# ═══════════════════════════════════════════════════════════════════════════
#  DINOv2 Finetuning — Configuration
# ═══════════════════════════════════════════════════════════════════════════
anno_root: ./preprocess/Phoenix14TCompressed
video_root: /kaggle/input/datasets/mariusschmidtmengin/phoenixweather2014t-3rd-attempt/videos_phoenix/videos
max_frames: 32

dino_model_name: facebook/dinov2-base
text_model_name: openai/clip-vit-base-patch16
spatial_input_dim: 768
proj_dim: 512

batch_size: 4
accumulate_grad_batches: 4
precision: 16
log_dir: logs/finetune_dino
